### ISSUE TITLE
Add close functionality to the "New Region" view

### ISSUE THREAD

**Issue by FuzzyReason** [medusajs/admin#124]
when selecting `Regions`  in settings and pressing `Add Region`  the interface doesn’t carry the `Cancel` button, so the user can close the form and get back to the regions list. 
![image](https://user-images.githubusercontent.com/62517920/136057878-655424c6-03d6-4168-a105-38abf0fb6eb9.png)

**Comment by Bhavin789** [comment]
Hello @FuzzyReason, since I am starting with React, would be great if I can have a look into it. Let me know if this can be assigned to me, would be happy to help 🙂. Thanks!!
