### ISSUE TITLE
Fulfillment Provider mapper should return a default object when id is unknown

### ISSUE THREAD

**Issue by srindom** [medusajs/admin#128]
If the fulfillment provider id is not known by [the fulfillment mapper](https://github.com/medusajs/admin/blob/master/src/utils/fulfillment-providers.mapper.js), it returns an empty string. It should return a default value that just has:
```
{
  label: provider,
  value: provider
}
```

Like in [the payment provider mapper](https://github.com/medusajs/admin/blob/master/src/utils/payment-providers-mapper.js).

**Comment by olivermrbl** [comment]
Closed #129
