### ISSUE TITLE
Missing save or cancel button on add note in timeline

### ISSUE THREAD

**Issue by sebastiannicolajsen** [medusajs/admin#154]
While it is possible to create a note by pressing enter, it is currently not possible to cancel the note as neither a save or cancel button as is proposed on the figma design:

![Skærmbillede 2021-10-18 kl  15 40 33](https://user-images.githubusercontent.com/80953876/137742958-db0c2b35-47dd-4b88-abce-0dc7145136be.png)

**Comment by olivermrbl** [comment]
Closed #201
