### ISSUE TITLE
Gift card is visible on the products overview page

### ISSUE THREAD

**Issue by sebastiannicolajsen** [medusajs/admin#159]
Currently, gift card is shown on `/a/products` which has multiple consequences, such as being able to copy it and attempt to modify it from the products page. Clicking modify brings the user to a blank page
![Skærmbillede 2021-10-18 kl  15 55 44](https://user-images.githubusercontent.com/80953876/137745381-59c399ea-47c8-48a9-8749-6da6ca1a686d.png)

**Comment by olivermrbl** [comment]
Solved in #530
