### ISSUE TITLE
Can't remove or edit options

### ISSUE THREAD

**Issue by inallermunde** [medusajs/admin#166]
Hello there,

When I add a custom option to the variants section of the product page it works, but when I try to remove that option or edit the name of it, it doesn't do anything. In the devtools i get a request to `/admin/products/<product_id>/options/undefined`. I don't think that's the right route?

**Comment by chemicalkosek** [comment]
Hey @olivermrbl Are you still working on this? The problem still exists. Can edit but can't remove.

Error on backend:
```
error:   Cannot read properties of undefined (reading 'options')
TypeError: Cannot read properties of undefined (reading 'options')
```
