### ISSUE TITLE
When receiving returns the shipping cost is not being accounted for in the refund amount

### ISSUE THREAD

**Issue by srindom** [medusajs/admin#167]
In admin:
- Click request return
- Add return shipping method
- Create return
- Click receive return
- Notice that the shipping cost is not accounted for in the refund currency-input box

Admin should show the refund amount as it is stored in the database and store operator should be able to change the refund amount between 0 (min) to cost of products (max).

**Comment by olivermrbl** [comment]
Duplicate of #522
