### ISSUE TITLE
All collections are not loaded in the product filter menu

### ISSUE THREAD

**Issue by srindom** [medusajs/admin#169]
## Reproduce
- Make sure you have at least 11 collections in your store
- Go to products
- Click Filter > Collection
- You will notice that you only see 10 collections to filter by

## Expected
All collections can be selected when filtering

___
This happens because the backend has a limit of 10 entities in the `/admin/collections` endpoint. We should probably add a "Load more" button underneath the bottom collection in the filter dropdown.

**Comment by olivermrbl** [comment]
Solved in #325
