### ISSUE TITLE
Can't select return shipping option, even though I created one

### ISSUE THREAD

**Issue by inallermunde** [medusajs/admin#172]
The dropdown in the request return, register swap and the register claim dialog does not show the return shipping option I created in `settings` -> `region settings` -> `edit region` -> `return shipping options`. In fact, the dropdown is empty. If I press complete when requesting a return or swap, i get an error in the server: "order cannot be swapped", and a popup in the admin ui saying it failed. I don't know if the error message is related to the fact that the return shipping option is missing.

**Comment by olivermrbl** [comment]
Hi @inallermunde ! Sounds very strange. Sorry, that it's causing you issues. Are you on Discord? Would love to reach out in direct message to hear more.

**Comment by inallermunde** [comment]
@olivermrbl yes i am. I'm gonna message you.

**Comment by olivermrbl** [comment]
This should be fixed running with latest Medusa version + admin. Let me know, if you are still experiencing issues :)
