### ISSUE TITLE
Feature-suggestion: Manage images

### ISSUE THREAD

**Issue by inallermunde** [medusajs/admin#173]
A page where you can see all uploaded images and can delete them or change their names, or other properties (you should probably also be able to upload images from here). And when you want to add an image (or a thumbnail) to a product, you get a popup where you can select one or more from already uploaded images, or upload a new one. I think Wordpress has a similar feature.

**Comment by srindom** [comment]
@inallermunde this is a great idea! We already have an Image table in the database so it should be fairly straightforward to create the admin screens that are needed to manage this in a nice way :)

**Comment by olivermrbl** [comment]
@adrien2p  - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our core project GitHub Discussions. That way, we centralize requested improvements, keep track of the demand (using the upvote mechanism), and streamline GitHub Issues around bugs. 

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
