### ISSUE TITLE
Product update is not working due to invalid type of inventory_quantity 

### ISSUE THREAD

**Issue by kennanseno** [medusajs/admin#180]
Error when editing product and changing inventory quantity

<img width="1334" alt="Screenshot 2021-11-29 at 16 34 04" src="https://user-images.githubusercontent.com/7852866/143834100-84aa9f62-2ae5-41ce-9dc8-7d42bf556101.png">

Error in logs:
TP/1.1" 204 0 "http://localhost:7000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36"
error:   inventory_quantity must be a number conforming to the specified constraints
Error: inventory_quantity must be a number conforming to the specified constraints

**Comment by olivermrbl** [comment]
Done! Thanks @kennanseno :)
