### ISSUE TITLE
Set up TailwindCSS

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/admin#193]
Add TailwindCSS to the project.

Follow official guide [here](https://tailwindcss.com/docs/guides/gatsby).

**Comment by rolwin100** [comment]
I'm taking this up

**Comment by rolwin100** [comment]
@olivermrbl assign it to me.

**Comment by olivermrbl** [comment]
Sure!

**Comment by rolwin100** [comment]
also @olivermrbl can we have a discussion about whether we shd create a new folder structure or go with the current implementation itself.

**Comment by olivermrbl** [comment]
Tailwind has been added to branch `feat/revamp-tailwind-init`. Feedback and input is more than welcome :)

**Comment by olivermrbl** [comment]
Closing this for now.
