### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by adrien2p** [medusajs/admin#209]
I think that there are still some responsive issues 

![image](https://user-images.githubusercontent.com/25098370/147694494-acae0ae8-f4b5-4989-9063-2deacc1c5dbb.png)

**Comment by kasperkristensen** [comment]
Hi @adrien2p, the admin is definitely still not responsive. We are currently in the process of giving our admin a facelift, and making it responsive is a part of that process. We are aiming to have the design implemented in Q1 of 2022 :)

**Comment by adrien2p** [comment]
Yeah I know that 😀 it was just in case. I got that on the last PR url preview 😊

**Comment by kasperkristensen** [comment]
Ahh all right! It's still very early stages, and the login has not been touched at all so far. So the previews of the revamp branches might look a little stange in the coming weeks, as we are doing the revamp one (or a couple of) components at the time 😁
