### ISSUE TITLE
Thumbnail inconsistencies

### ISSUE THREAD

**Issue by VilfredSikker** [medusajs/admin#28]
The thumbnail picker sometimes chooses a different image than the chosen one. 
This seems to happen if you've previously saved a thumbnail and in the same session creates a new thumbnail on another product.

**Comment by rolwin100** [comment]
@VilfredSikker Pls elaborate more on the steps to replicate it. I'm not even understanding where is the thumbnail present.

**Comment by VilfredSikker** [comment]
Thanks for checking. This is an outdated issue. It's replaced by images👏🏻
