### ISSUE TITLE
Admin revamp: SETTINGS (bug-hunt)

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/admin#298]
Join in on our bug-hunt on [Discord](https://discord.gg/medusajs)!

- [ ] Dropdown positioning -> Should overflow parent div
- [x] Typo in Currencies subtitle
- [ ] Wrong description for Return Reasons
- [x] Can add return reason without value
- [ ] Placeholders in User Information
- [x] Can add Region without name
- [ ] Mismatch between shipping option currency and region currency
- [x] Store name in Settings does not change the name in nav bar
- [ ] ^ Also accepts an empty string
- [ ] Member count is not changed in team overview
- [ ] Scroll bar should not appear if container is not scrollable
- [x] No error on wrong credentials

**Comment by ymaheshwari1** [comment]
@olivermrbl It will be good if we can mark the list option as completed which are handled in a PR, like an issue of `No error on wrong credentials` is handled, so that no other person starts working on it.
