### ISSUE TITLE
Can't update inventory quantity on revamped admin

### ISSUE THREAD

**Issue by Blechlawine** [medusajs/admin#334]
I feel like this is an important feature and I already mentioned it in the discord.
Basically, the 2 ways of editing the inventory quantity of a product/variant don't work, one of them is not being sent to the server, the other one can't be modified because of an undefined function prop.

I did some digging in the source code and found this for the latter one:
When trying to change the inventory quantity in the new admin in the variants panel, it throws an error in the console` onChange is undefined`, because in `/components/variant-grid/index.js:154` it tries to call a function, that the parent component should have, but in `/domain/products/product-form/sections/variants.tsx:40` onChange is not defined as a prop on the VariantGrid component.

I'm creating this issue for people who look at the github issues and who have a better understanding (than me) of gatsby and react to fix this/help me fix this.

**Comment by Blechlawine** [comment]
@olivermrbl So I did some more digging, and found 2 files named index in my variant-grid component folder on index.js and one index.tsx. according to the git commit history, the .tsx file is the newer one. But my admin still loaded the index.js file for the variant-grid. I So i renamed the .js file to something else, and lo and behold, now the variant-grid works for editing inventory quantity.
I don't know if the index.js is still needed somewhere, but if it is not, then it should probably be removed.

**Comment by olivermrbl** [comment]
Well spotted! Should definitely not be there.

It will be removed as part of #327 in which we fix all of the hanging issues w. the variant grid

**Comment by nielswart** [comment]
I found a related issue.  I'm able to update inventory, but the manage inventory checkbox state does not get saved:

If I open the product page, I get this:

![image](https://user-images.githubusercontent.com/2334546/157176761-91396965-a338-4b28-8003-19b6f66d0638.png)

I then check the Manage Inventory checkbox, update the inventory and click save:

![image](https://user-images.githubusercontent.com/2334546/157176895-8777a25a-90d2-45f1-8e0c-f5b9dd2408de.png)

This is the payload that is sent with the POST request on save:

![image](https://user-images.githubusercontent.com/2334546/157177228-d934bab6-3648-4054-bcd8-1ffd865dfbcc.png)

And this is what the GET response looks like:

![image](https://user-images.githubusercontent.com/2334546/157177353-7da57d6f-860f-420c-9483-9816d76a8fe4.png)

**Comment by olivermrbl** [comment]
Solved in #393
