### ISSUE TITLE
If you modified fields in a maintenance window, it should prompt you if you want to leave the page

### ISSUE THREAD

**Issue by jzatarain** [medusajs/admin#369]
For example, if I start capturing a new item, and I refresh or open another page inside the app, I may end up losing what I wrote.
Either the prompt could work,  or it could maintain the data in-memory.

**Comment by jzatarain** [comment]
I don't know how to add tags, or if I can do it.

**Comment by olivermrbl** [comment]
Thanks for reporting it in. Unfortunately, this is not something we'll add support for in the near future. Will make a note of it!
