### ISSUE TITLE
[Feature] Internationalisation (I18n)

### ISSUE THREAD

**Issue by adrien2p** [medusajs/admin#405]
At the moment, the entire application is in english, which is the common language for everybody.

If I want to be able to use the project, I would need to fork it and update everything to either be in my own language or implement
the internationalisation my self. 

That means that  if the project evolve (which is the case) I would have to follow and manage all the conflict than this update would provoke.

For that reason, it can be a blocking point for some users.

**Comment by adrien2p** [comment]
as mention in discord
https://discord.com/channels/876835651130097704/877195433649258536/950521209093754940
https://discord.com/channels/876835651130097704/877195433649258536/950521637340577904

@olivermrbl if you could have a look and I let you answer Alex about the final choice, if that can be referenced here then please :)

**Comment by edihasaj** [comment]
Any news on this?

**Comment by olivermrbl** [comment]
@adrien2p  - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our core project GitHub Discussions. That way, we centralize requested improvements, keep track of the demand (using the upvote mechanism), and streamline GitHub Issues around bugs. 

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
