### ISSUE TITLE
I fully followed tutorial, but getting errors

### ISSUE THREAD

**Issue by vavdav** [medusajs/admin#407]
I have followed this tutorial https://docs.medusajs.com/tutorial/creating-your-medusa-server and readme of this repo https://github.com/medusajs/admin

I have been getting errors from the very beginning, and also I am not able to create any products.

On page load:
<img width="703" alt="Screen Shot 2022-02-27 at 21 54 38" src="https://user-images.githubusercontent.com/215969/155899603-685a1e30-ec0d-406c-b47e-34960f6cc6f2.png">

When creating a product:

<img width="754" alt="Screen Shot 2022-02-27 at 21 59 02" src="https://user-images.githubusercontent.com/215969/155899692-3596cad6-6328-4714-888c-9b488c210436.png">
<img width="713" alt="Screen Shot 2022-02-27 at 21 58 28" src="https://user-images.githubusercontent.com/215969/155899693-c570d2a6-e2ad-4693-bd2a-c4f7c42504ce.png">

I am not sure what I am doing wrong

**Comment by vavdav** [comment]
I also tried using that docker-compose file, but having problems with PostgreSQL (but I am able to connect with dbeaver without any issues)
<img width="773" alt="Screen Shot 2022-02-27 at 22 51 39" src="https://user-images.githubusercontent.com/215969/155901459-b5684e60-4303-4bec-8dbf-2e382b9593f4.png">

**Comment by vavdav** [comment]
@olivermrbl I am still getting the same errors. I did packages updates. Just resolved `docker-compose` issue.

**Comment by olivermrbl** [comment]
Hey @vavdav! I mistakenly closed your issue - sorry. The 401 error you are seeing when opening admin is because you are unauthorized. The error modal looks more dangerous than it is. You can close it down and sign in with `admin@medusa-test.com // supersecret`. The error 500 probably stems from the fact, that you do not have a file service installed. File services are responsible for the hosting of product images. You can check out our guide on adding a file service plugin [here](https://docs.medusajs.com/add-plugins/spaces).

Will reopen until we've resolved your issues 👍

**Comment by vavdav** [comment]
Oh thanks @olivermrbl . It was not clear to me from the guide that I have to setup the file service. I also tried https://docs.medusajs.com/how-to/create-medusa-app without success.
I will check it.

**Comment by han-tyumi** [comment]
@olivermrbl I'm also running into a 401 issue.
I get this error which crashes the server after trying to open the page.
I've followed both the Quickstart Guide and Using create-medusa-app pages - both lead to the same issue.

```
Error: You must provide the URL of lib/mappings.wasm by calli
  ng SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... })
   before using SourceMapConsumer
  
  - read-wasm.js:8 readWasm
    [admin]/[gatsby]/[source-map]/lib/read-wasm.js:8:13
  
  - wasm.js:25 wasm
    [admin]/[gatsby]/[source-map]/lib/wasm.js:25:16
  
  - source-map-consumer.js:264 
    [admin]/[gatsby]/[source-map]/lib/source-map-consumer.js:26
    4:14
  
  - task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5
  
  - stack-trace-utils.ts:122 findOriginalSourcePositionAndConte
    nt
    [admin]/[gatsby]/src/utils/stack-trace-utils.ts:122:10
  
  - start-server.ts:457 
    [admin]/[gatsby]/src/utils/start-server.ts:457:20
```

<img width="800" alt="image" src="https://user-images.githubusercontent.com/13040345/166083081-4ace02b6-bcdf-4740-b196-9991f734cb88.png">

**Comment by olivermrbl** [comment]
@han-tyumi This is identical to the issue initially described in the issue here. The error is shown because you are not authorized yet. Should be resolved by signing in to admin. Will close fow now, but reopen in case your issue persist 👍
