### ISSUE TITLE
Drag and drop product variants to change sorting in products

### ISSUE THREAD

**Issue by VilfredSikker** [medusajs/admin#42]
A good choice would be to use `react-use-gesture` together with `react-spring`
https://www.npmjs.com/package/react-use-gesture
https://www.npmjs.com/package/react-spring

**Comment by olivermrbl** [comment]
Glad to hear @NayeBeckham ! We are in the process of redesigning our admin system, so it might not make too much sense to start the implementation now. I will make sure to ping you as soon as we have a new design ready for the products page. Is that cool with you? :)

**Comment by NayeBeckham** [comment]
All right, thank you!
