### ISSUE TITLE
Draft orders - Go to order button has wrong link

### ISSUE THREAD

**Issue by Kyle772** [medusajs/admin#421]
Draft Order -> mark as paid -> Go to order (top)
This button has a "}" appended to the end of the link

![Screenshot_select-area_20220304195159](https://user-images.githubusercontent.com/995633/156866739-f80c7d22-72e3-44fd-b5e3-c7551af0d104.png)

ie "/a/orders/order_01FXC37KQENJK8E3CC9E9B47HW}"

**Comment by olivermrbl** [comment]
Solved in #603
