### ISSUE TITLE
`.csv` reader initial implementation

### ISSUE THREAD

**Issue by kasperkristensen** [medusajs/admin#438]
We want to add a `.csv` reader component/utility to our admin, to perform bulk imports. Initially it will be used for the new price list UI. 

We will be implementing ways to handle parsing and gathering the required data server side, but for now we want to implement a MVP version where the file is parsed client side, and then makes the necessary requests to the server.

We also want to add this functionality to importing other entities such as products, so keep the component/utility generic so it can be reused for other domains.

Could use something like [react-csv](https://www.npmjs.com/package/react-csv) for the implementation.

See Figma: https://www.figma.com/file/a5Mb7n6lelmmFU28wqQybY/Customer-Groups%2C-Promotions-%26-Pricing?node-id=494%3A12226

**Comment by adrien2p** [comment]
Implementing the csv parser server side will not be that difficult, I think we should go for that directly and created in the parser directory maybe?

**Comment by olivermrbl** [comment]
Closing since we will be parsing CSV files server-side
