### ISSUE TITLE
Fresh Installation Admin only accesible from localhost

### ISSUE THREAD

**Issue by Higherings** [medusajs/admin#454]
Hello, I have followed all the directions to install de Medusa Admin:
git clone https://github.com/medusajs/admin medusa-admin
cd medusa-admin
yarn install
yarn start

And all went fine but the Admin is only accessible from localhost. How can we enable to be accesible from the server IP ?

Kind Regards.

**Comment by olivermrbl** [comment]
@Higherings  Can I get you to elaborate a bit on the request? 

Are you looking to deploy admin to a production environment, or just change the host when running it locally?

**Comment by Higherings** [comment]
Hello @olivermrbl, I would like to deploy Admin to a Production Environment. I want to be able to access it externally.

**Comment by olivermrbl** [comment]
@Higherings I recommend checking out our [guide](https://docs.medusajs.com/how-to/deploying-admin-on-netlify) for deploying admin on Netlify 👍

**Comment by olivermrbl** [comment]
Closing this, since it's not an issue, but the standard way of setting up a Gatsby project

**Comment by Higherings** [comment]
Thanks @olivermrbl for pointing where to search information. Just as a comment, it would be great if the README could have a Production Deployment Guide without using any other platform.
