### ISSUE TITLE
UI: Implement Promotions Code Input

### ISSUE THREAD

**Issue by zakariaelas** [medusajs/admin#465]
We should create a field for promotion code which when empty, will show a text "generate" to the right. Clicking the text should generate a promotion code automatically. The "generate" text button will be replaced by a "refresh" icon to generate a new promotion code. See design [here](https://www.figma.com/file/a5Mb7n6lelmmFU28wqQybY/Customer-Groups%2C-Promotions-%26-Pricing?node-id=649%3A12033)

**Empty state: Input with "Generate" text button**
<img width="466" alt="image" src="https://user-images.githubusercontent.com/33696020/160414993-fbd4b234-5e81-409d-b3fd-7b2959b1ae3b.png">

**Filled state: Input with "refresh" icon**
<img width="344" alt="image" src="https://user-images.githubusercontent.com/33696020/160415107-6691c259-6250-4ec2-8bd6-8ffe01b927c0.png">

The PR should also include a utils method `generatePromotionCode()` responsible for generating a promotion code

**Comment by olivermrbl** [comment]
For the util, we could leverage npm library `randomatic` and do:
```
  import randomize from "randomatic"

  generateCode_() {
    const code = [
      randomize("A0", 4),
      randomize("A0", 4),
      randomize("A0", 4),
      randomize("A0", 4),
    ].join("-")

    return code
  }
```

Would be similar to how they are generated in the core.
