### ISSUE TITLE
Collection thumbnail image

### ISSUE THREAD

**Issue by wouter-dev** [medusajs/admin#486]
Would be lovely to set a collection thumbnail image instead it takes a random image from a product in the collection

**Comment by kasperkristensen** [comment]
Hi @wouter-dev, it's a great idea and something we have talked about previously. We will be taking a look at expanding on some of our core models this quarter, and we will definitely consider adding this to collections :)

For the time being could add a thumbnail to a collection, by adding it to the collections metadata.

Then you could have a collection like this:

```json
{
  "id": "pcol_12324252525"
  // ...
  "metadata": {
    "thumbnail": <url_to_thumbnail",
  }
}
```

This way you can also add anything you would like such as a description, or anything else you would like to add :) I'm guessing you are referring to the Gatsby starter where it just picks a random thumbnail from the products in the collection. To use the above approach for setting a thumbnail on a collection, you would then simply have to change the `useCollections` hook that generates the collection previews data, as such:

```js
export const useCollections = (collections = [], products = []) => {
  const collectionPreviews = useMemo(() => {
    return collections.edges.map(({ node }) => {
      const { id, title, handle, metadata } = node <-- changed this
      const prods = products.edges.filter(
        ({ node }) => node.collection_id === id
      )

      return {
        id,
        title,
        handle,
        thumbnail: metadata.thumbnail <-- and this
      }
    })
  }, [collections, products])

  return collectionPreviews
}
```
And also change the `<CollectionPreview />` component:

```jsx
const CollectionPreview = ({ collection }) => {
  return (
    <Link to={`/collections/${collection.handle}`}>
      <div className="group relative">
        <div className="w-full min-h-auto bg-gray-200 aspect-w-1 aspect-h-1 rounded-md overflow-hidden group-hover:opacity-75 lg:h-80 lg:aspect-none">
          <GatsbyImage
            image={collection.thumbnail} // changed this
            alt={`Item from the ${collection.title} collection`}
            className="w-auto h-full object-center object-cover"
          />
        </div>
        <div className="mt-4">
          <h3 className="text-sm text-gray-700">
            <p className="font-normal">{collection.title}</p>
          </h3>
        </div>
      </div>
    </Link>
  )
}
```
