### ISSUE TITLE
bug(orders): cancelling claim results in 404

### ISSUE THREAD

**Issue by srindom** [medusajs/admin#505]
`useAdminCancelClaim` expects an order id but is given a claim id resulting in a 404 when POSTing to `/admin/orders/[claim_id]/claims/[]/cancel`

`event.id` on L25 should be changed to the order id and the claim id should be added when performing the mutation i.e.: `cancelClaim.mutate(event.id)`.

https://github.com/medusajs/admin/blob/master/src/components/molecules/timeline-events/claim/index.tsx#L25

To test:
- Create an order
- Create a claim
- Cancel claim

**Comment by olivermrbl** [comment]
Solved in #534
