### ISSUE TITLE
bug(products): Saving product should not default to publish the product too

### ISSUE THREAD

**Issue by srindom** [medusajs/admin#518]
**Steps to reproduce**
- Create a product
- Set the product status to draft
- Change the name of the product and hit save

At this point the product should still be in draft, however, the save call defaults to sending `status: published` this should be fixed so that it saving a draft product doesn't change the status.

The file to change is here: https://github.com/medusajs/admin/blob/8189ab1c6b5cf2f92a226da30f7d665e7c8b39f9/src/domain/products/product-form/form/mappers.ts

**Comment by olivermrbl** [comment]
Solved in #532
