### ISSUE TITLE
bug(orders): receiving return with return shipping results in wrong refund amount

### ISSUE THREAD

**Issue by srindom** [medusajs/admin#522]
**Steps to reproduce**

- Create an order 
- Fulfill and ship the order
- Create a return and add a return shipping method with a price > 0
- Receive the return

At this point the refund amount sent to the backend only takes the product total into account: i.e. the shipping cost is not deducted from the refund amount and the customer, therefore, receives a higher discount than they are supposed to.

**Comment by pKorsholm** [comment]
Has this already been solved, I cant seem to reproduce with the given steps

**Comment by olivermrbl** [comment]
Solved #539
