### ISSUE TITLE
Bug: duplicating a product results in handle and description being "undefined"

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/admin#537]
this occurs because the fields included in the query to list-products are limited to what is shown in the table, and don't include description or handle. 

When the product is duplicated the fields are copied from the row entity which lacks some of the fields. 

possible solutions: 
- include fields in list products query
- fetch the product when duplicating it to ensure all the proper fields are included

**Comment by olivermrbl** [comment]
I can't seem to reproduce this issue in the latest release. Closing for now. Let me know if you are still experiencing this after having updated your project.
