### ISSUE TITLE
sale_amount is missing in the admin theme

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/admin#550]
It came up in a discord discussion that a property of `sale_amount` exists on a product/variant which can be used to have a sale price.

Seems that property is missing in the admin theme.
Relevant discord link: <https://discord.com/channels/876835651130097704/877195433649258536/969675223274225664>

**Comment by kasperkristensen** [comment]
@chemicalkosek `sale_amount` has been removed in the latest version of Medusa. Going forward, you will define sales using the new `PriceList` entity: https://github.com/medusajs/medusa/blob/master/packages/medusa/src/models/price-list.ts. We are working on adding a new Prices section to the admin where you will manage this from, which will be released soon 😄
