### ISSUE TITLE
Cannot Create 2 products in a row without refresh

### ISSUE THREAD

**Issue by dwene** [medusajs/admin#580]
If I attempt to create 2 products in a row without a hard refresh, the form errors and attempts to use old cached data.

https://www.loom.com/share/8140831da8c44e5ebca890afa781663d

Expected Result:
Can create 2 products, and creating second product does not attempt to use previously created product data.

To Reproduce:
Running on the latest `develop` branch as of May 29, 2022.

**Comment by olivermrbl** [comment]
Solved in #637
