### ISSUE TITLE
Cannot View Discounts

### ISSUE THREAD

**Issue by dwene** [medusajs/admin#582]
https://www.loom.com/share/ee2e1f66fb754664be1cfcb6dda9aded

Expected Result: Can view and modify a discount
Actual Result: There is an error thrown preventing the view from loading.
Reproduce: Latest `develop` branch

**Comment by kasperkristensen** [comment]
Hi @dwene,

Thanks for reporting the issue, it's because the discounts in the current version of `develop` is still wired up to work with how discounts were pre `1.3`. Will be fixed once #536 is merged 😄
