### ISSUE TITLE
Adding shipping option should let user choose whether the price is flat rate or calculated

### ISSUE THREAD

**Issue by macder** [medusajs/admin#597]
Currently, when adding a shipping option to a region, it is always a flat rate. There should be an option to choose the price type

The `price_type` is currently hard-coded to `flat_rate` in https://github.com/medusajs/admin/blob/a33ed20214297ffdbd2383f809dddd4870f5dad9/src/domain/settings/regions/new-shipping.tsx#L85

This prevents saving new shipping options that get calculated using a fulfullment provider

**Comment by umer2001** [comment]
@macder can you assign it to me?
I will add a selection in **ShippingOptionForm**
