### ISSUE TITLE
Can not edit discount created without conditions

### ISSUE THREAD

**Issue by edsonsantoro** [medusajs/admin#598]
If the user creates a discount without any conditions, it will be impossible to edit this discount. Error screen:

![image](https://user-images.githubusercontent.com/4317016/172828161-f3244bd2-9e15-49d5-b981-b5191c207457.png)

Problem line: 
https://github.com/medusajs/admin/blob/a33ed20214297ffdbd2383f809dddd4870f5dad9/src/domain/discounts/details/conditions/use-discount-conditions.tsx#L27

We are trying to use `map` on undefined `conditions`.

How to reproduce: 
Create a discount without conditions and try to edit after saved as draft or published.

**Comment by olivermrbl** [comment]
I can't seem to reproduce this issue with latest Medusa version and admin release. Closing for now. Let me know if you are still experiencing it after updating
