### ISSUE TITLE
Deleting Metadata

### ISSUE THREAD

**Issue by Savvy** [medusajs/admin#601]
Metadata in collections are not supported by core therefore not possible in admin.

**Comment by olivermrbl** [comment]
@Savvy - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
