### ISSUE TITLE
CORS Error when using GATSBY_MEDUSA_BACKEND_URL env variable

### ISSUE THREAD

**Issue by cboydstun** [medusajs/admin#604]
My server deployed to Heroku successfully. Unfortunately, deploying my Admin panel gave continued CORS errors when interacting with the backend despite properly updated environment variables. 

The issue appears to be with the environmental variable `GATSBY_MEDUSA_BACKEND_URL` not taking precedence during loading. I overcame this issue in the Admin project in Chrome and FireFox on a _local_ development with deployed Medusa backend server:

1. Open Gatsby Admin project
2. Go to file `config.js` inside `src\services` directory -> change line 3 to `let medusaUrl = "YOUR DEPLOYED MEDUSA SERVER"`
![image](https://user-images.githubusercontent.com/52934303/173573989-ed60f0c8-6241-4cb7-bf0e-a8763a2bc38a.png)
3. Go to file `request.js` inside `src\services` directory -> change line 3 to `let baseURL = "YOUR DEPLOYED MEDUSA SERVER"`
![image](https://user-images.githubusercontent.com/52934303/173574023-3189ed05-53d5-453a-ba49-b0662858c72d.png)
No more issues after changing those two variables and removing `GATSBY_MEDUSA_BACKEND_URL` as an environmental variable from the Admin project! Also, to apply this solution, delete the `ADMIN_CORS` variable from your deployed Medusa server so that it defaults back to the `localhost:7000` that it is expecting. I'll be working on getting it all deployed today so stay tuned! 😃

Update: I'm not able to comment in the Discord, but found my solution while reading [this chat](https://discord.com/channels/876835651130097704/877195433649258536/984477455899295754) and this other [storefront issue](https://github.com/medusajs/medusa/issues/446).

**Comment by olivermrbl** [comment]
@cboydstun Glad to hear it worked out!

Irt. not being able to comment in Discord, can I get you to elaborate? Have not heard of it before.
