### ISSUE TITLE
Custom header for medusa requests

### ISSUE THREAD

**Issue by Inoir** [medusajs/admin#629]
We wanted to use medusa with multi tenancy system and therefore we need some custom headers defined in every request send to medusa.

Currently this is not possible, cause of useage of an private non open source module called "medusa-react". First of all, why use an non open source library in an open source project? Its not possible to extend or add header in this api calls made there.

Please either get rid of this lib, or extend it so you can pass a config into axios, or make it public.

**Comment by Inoir** [comment]
Got it working with setting header on default axios settings:

```
import axios from "axios"

axios.defaults.headers.common["X-Tenant"] = "XXXX"
```

**Comment by kasperkristensen** [comment]
Hi @Inoir, great that you found a solution. Just FYI, medusa-react is also open sourced and you can find the source code for it right here: https://github.com/medusajs/medusa/tree/master/packages/medusa-react 😄
