### ISSUE TITLE
On slow network, `hi index` message is displayed if the orders page takes time to load

### ISSUE THREAD

**Issue by ymaheshwari1** [medusajs/admin#643]
Sometimes after login, a message `hi index` is displayed on the orders page until the page does not load completely.

Instead, a more meaningful message should be displayed like `Welcome to Admin` or something else, even instead of displaying a message a loader can also be displayed.

**Comment by ymaheshwari1** [comment]
I'm interested in working on this.

**Comment by olivermrbl** [comment]
That would be great! I'll loop our designer @ludvig18 in here. He might be able to come up with something nice 👍
