### ISSUE TITLE
Use ViteJS-React with TypesScript instead of Gatsby for the core Admin Panel. It slow down development by a lot.

### ISSUE THREAD

**Issue by edardev** [medusajs/admin#646]
There is not need for building the Core Admin planel with Gatsby, it slow down development by a lot.

https://vitejs.dev/

**Comment by olivermrbl** [comment]
We don't have plans of migrating admin to ViteJS any time soon. Will reopen the issue, if it becomes relevant :)

**Comment by edardev** [comment]
> 

You can use React with Vite, or anything faster. It does make sense to use Gatsby for the Admin panel other thant the storefront, lol
