### ISSUE TITLE
Order page doesn't show which variant is ordered.

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/admin#651]
On the order page, store administrator can't see which variant of product is ordered.
Also if product title is too long it gets truncated on the order page.

**Comment by AksHaYGuPTa28** [comment]
Hello @olivermrbl, can I work on this issue, can we add more description?

**Comment by chemicalkosek** [comment]
Actually it looks like it was fixed down the road already

**Comment by olivermrbl** [comment]
Closing, as the reported issue has been resolved. Will create a ticket internally for the title truncation issue.
