### ISSUE TITLE
Stop the pulling the Redis service - Free tier from Upstash, exceeded limit 10000 usage in few minutes!.

### ISSUE THREAD

**Issue by edardev** [medusajs/admin#654]
From upstash -redis:
ERR max daily request limit exceeded. Limit: 10000, Usage: 10000. See https://docs.upstash.com/overall/databasetypes for details

**Comment by edardev** [comment]
![image](https://user-images.githubusercontent.com/21114220/180329661-c3cb45ae-1083-4212-a218-b31e59ca2619.png)

**Comment by olivermrbl** [comment]
This is not relevant to the admin system. If the issue persists, please open an issue in [our core repo](https://github.com/medusajs/medusa).
