### ISSUE TITLE
[Bug] Select options not visible untill clicking twice

### ISSUE THREAD

**Issue by ymaheshwari1** [medusajs/admin#655]

**Comment by kasperkristensen** [comment]
Hi @ymaheshwari1,

Could you please elaborate a bit on this? 😄

**Comment by ymaheshwari1** [comment]
> Hi @ymaheshwari1,
> 
> Could you please elaborate a bit on this? 😄

Will add details on this.

**Comment by kasperkristensen** [comment]
Closing this, as it is related to the "old" version of our select component which we are phasing out.
