### ISSUE TITLE
[Bug] Pagination label is customers on customer groups page

### ISSUE THREAD

**Issue by ymaheshwari1** [medusajs/admin#656]
Issue:
![Screenshot (183)_LI](https://user-images.githubusercontent.com/41404838/180659408-4bed4564-051c-4f77-b3af-31b232a4465f.jpg)

Expected:
It should be `1-1 of 1 groups` or `1-1 of 1 customer groups`

**Comment by ymaheshwari1** [comment]
I'm interested in working on this.

**Comment by kasperkristensen** [comment]
Hi @ymaheshwari1, a PR would be appreciated 😄
