### ISSUE TITLE
gatsby for an admin?

### ISSUE THREAD

**Issue by osseonews** [medusajs/admin#657]
I'm just curious why you chose to use Gatsby to build an admin dashboard? Gatsby seems more suited to a static website, and a dashboard is fully dynamic. Seems like there is a ton of reinventing of the wheel here. Why not just build off of React-Admin (https://marmelab.com/react-admin/). As you are already using React-Query, React-Hook-Form, I would guess you can build a complete React-Admin dashboard for Medusa in a few weeks, and save yourself tons of time, debugging etc.  Plus it would be much easier to get contributors for the admin dashboard, as React-Admin is very popular and the structure is much easier to follow than a custom Gatsby dashboard.

**Comment by edardev** [comment]
I love Gatsby but It does make sense to use Gatsby to build a separate Admin panel. Gatsby is a great choice for the storefront website. It is slow for development and brings extra boilerplate that it is not need for this use case. I would recomend to use Vite.js with React and/or Typescript.

**Comment by edardev** [comment]
I can help with the migration, it shouldn't be difficult as it will be migrating to react with a smaller bundler and faster compiler.

**Comment by kasperkristensen** [comment]
Hi @osseonews,

The choice of Gatsby simply stems from the fact that it was what was the most familiar to our founding team when they first began building out the initial admin dashboard several years.

I agree on the use of Gatsby not being relevant for this type of application, and that we could improve build times, etc. by trimming down the admin to a plain React application. It's definitely something we will look into when the time is right, but not something we have planned for our roadmap atm. 

Closing this issue as there is already an open issue that is similar to this 😄
