### ISSUE TITLE
[Bug] Error after sign-in on admin

### ISSUE THREAD

**Issue by ymaheshwari1** [medusajs/admin#662]
Screenshot:

![Screenshot (184)](https://user-images.githubusercontent.com/41404838/181925031-27e88c3d-9681-478f-a4e8-f6edb511a0fc.png)

**Comment by pKorsholm** [comment]
Hi, Thanks for reporting. 

The issue should be fixed by this pr: https://github.com/medusajs/admin/pull/663

You should be able to run medusa admin from that branch until it's merged 😄

**Comment by olivermrbl** [comment]
Solved in #663
