### ISSUE TITLE
Can't view customer page

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/admin#664]
Steps to reproduce:
1. Click on any customer in admin dashboard
2. It redirects to customer page, but the page is blank

Browser console error:
```
 TypeError: Cannot read properties of undefined (reading 'slice')
    at index.tsx:33:39
    at index.tsx:67:50
```

Which is from here: https://github.com/medusajs/admin/blob/d79c68cf9a533741434aaff21c1adaa35f113ee2/src/components/templates/customer-orders-table/index.tsx#L34

It might be that `items` relation is not returned in the `useAdminOrders` hook as I don't see it in a console.log

**Comment by olivermrbl** [comment]
Fixed in #649
