### ISSUE TITLE
Mobile Responsive Design

### ISSUE THREAD

**Issue by Keith-Hon** [medusajs/admin#679]
Update the UI to have mobile responsive design

**Comment by kasperkristensen** [comment]
Hi @no-1ne 

No ETA, but we will be working on implementing a new design system / component library for the admin in 2023, and we will definitely be looking to make it more responsive :)

**Comment by olivermrbl** [comment]
@Keith-Hon - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
