### ISSUE TITLE
Unable to add new Currency Code

### ISSUE THREAD

**Issue by feelfetch** [medusajs/admin#695]
I've been trying to add a new currency following the "Add a Currency Code" section in the docs [link](https://docs.medusajs.com/api/admin/#tag/Store/operation/PostStoreCurrenciesCode)

`curl --location --request POST https://wl-store.herokuapp.com/admin/store/currencies/eur --header "Authorization: Bearer {api_token}"
`

Edited the Postgres DB to include the API Token for the user, but I get a general error reply and I really do not understand why.

`{"code":"unknown_error","type":"unknown_error","message":"An unknown error occurred."}`

Any idea?

**Comment by olivermrbl** [comment]
What version of `@medusajs/medusa` are you using?

**Comment by feelfetch** [comment]
Deployed a server to Heroku so I guess it should be "@medusajs/medusa": "^1.3.1",

**Comment by feelfetch** [comment]
Nevermind, upgrading to 1.4.0 solved my issue.
