### ISSUE TITLE
Can't select thumbnail from existing images

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/admin#708]
In the new, lately revamped product page you can't select a thumbnail from existing images.
You need to upload a new image each time you want to change thumbnail.
Previously you could mark an image as thumbnail.

**Comment by olivermrbl** [comment]
@chemicalkosek - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
