### ISSUE TITLE
Bug: General validation in forms

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/admin#72]
**What?**
- Forms need general validation of required fields before submission

**Comment by rolwin100** [comment]
@pKorsholm can u list all the places where the validations are needed.

**Comment by pKorsholm** [comment]
The idea is to highlight which fields are missing to the user so they can easily identify which fields are missing data

Ideally this would apply to any form in the admin portal with required fields, I might have missed some, but here is a list:
- When creating an order
- When creating a discount
- Product creation/update
- Region details

Thanks a lot Rolwin 😄

**Comment by rolwin100** [comment]
ur welcome @pKorsholm :)
