### ISSUE TITLE
Clicking Refund without sufficient balance at Stripe yields generic error.

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/admin#720]
When clicking Refund on admin dashboard it fails with `Error. 
An unknown error occurred.
` when Stripe Balance has insufficient funds for refund.

The backend logs show the proper error message though:
```bash
 {"level":"error","message":"Insufficient funds in your Stripe balance to refund this amount.","stack":
 ```

**Comment by olivermrbl** [comment]
Thanks for filing this @chemicalkosek. Can I get you to move this to our core repository if it is still relevant?
