### ISSUE TITLE
Region settings display stripe payment provider as fulfillment provider

### ISSUE THREAD

**Issue by artkaas** [medusajs/admin#728]
Define a region, add Stripe as payment provider to the region. It is displayed as both payment provider (which is ok) but also fulfillment provider (which is not ok), as seen on the screenshot:

<img width="1307" alt="admin-bug" src="https://user-images.githubusercontent.com/23141356/195191016-f4dbc1b5-f9aa-4d8d-a29f-af86df83fe04.png">

**Comment by olivermrbl** [comment]
Nice catch! Will be fixed in upcoming release 💪
