### ISSUE TITLE
Medusa admin not working

### ISSUE THREAD

**Issue by Namankataria01** [medusajs/admin#731]
Medusa admin not working it gives an babbel error

**Comment by Namankataria01** [comment]
![Uploading beeel.jpg…]()

**Comment by Namankataria01** [comment]
React Refresh Babel transform should only be enabled in   
development environment. Instead, the environment is: "dev". If you want to override this check, pass 
{skipEnvCheck: true} as plugin options.

**Comment by Namankataria01** [comment]
React Refresh Babel transform should only be enabled in   
development environment. Instead, the environment is: "dev". If you want to override this check, pass 
{skipEnvCheck: true} as plugin options.

**Comment by Namankataria01** [comment]
![beeel](https://user-images.githubusercontent.com/77058598/195547883-9470f6b9-67b3-4d89-9663-ba2d7d29a2b4.jpg)

**Comment by olivermrbl** [comment]
Can I get you to add reproducible steps? This seems specific to your setup, so hard for us to debug.

**Comment by Namankataria01** [comment]
i just created  a project from the create medusa app
that's it

**Comment by Namankataria01** [comment]
solution set NODE_ENV=development it will work

**Comment by kasperkristensen** [comment]
Closing as the issue was resolved in discord. For anyone else that stumbles across this, it's not the default behavior but related to OP local setup.
