### ISSUE TITLE
Feat: add tooltip to 'handle' field

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/admin#74]
**What?** 
- in 'Collection creation' and 'Product information' there is no indication of what the 'Handle' field does

'Handle' is an alternative that can be used in the url of the webshop when accessing a product instead of the database id. 
i.e. "Basic-t-shirt" instead of "prod_01FEGMPRK...."

**Comment by rolwin100** [comment]
I'm taking this up @olivermrbl

**Comment by rolwin100** [comment]
I have created a PR to develop https://github.com/medusajs/admin/pull/83 can you close this @olivermrbl

**Comment by olivermrbl** [comment]
Closed #84
