### ISSUE TITLE
Variant badges overflowing when you have too many.

### ISSUE THREAD

**Issue by chiubaca** [medusajs/admin#749]
I've loaded in a product with 49 variants and noticed that it's spilling over the container:

![image](https://user-images.githubusercontent.com/18376481/197528573-f8c096e3-7f8e-44b0-b9b2-589d8012badb.png)

adding `overflow: scroll;` to the parent container with a bit of padding seems like a quick fix for this:

https://user-images.githubusercontent.com/18376481/197529061-ab45988d-a2ab-4c4a-9745-9b1ff13d1a1d.mov

Happy to raise a PR to fix :)

**Comment by kasperkristensen** [comment]
Hi @chiubaca

Thanks for reporting the issue, but this has been fixed on the `development` branch (#715), which we will release later this week. 👍
