### ISSUE TITLE
Bug: improve 'Tags' tooltip in product information

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/admin#75]
**What?**
- The tooltip for the 'Tags' field in product information could be more expressive

**Comment by rolwin100** [comment]
what change needs to be done @pKorsholm can you elaborate more. Please provide more description for other issues as well @pKorsholm

**Comment by pKorsholm** [comment]
This tooltip is not very indicative of what a tag is or does.

The tooltip text needs to be more elaborate i.e. "Tags are one word descriptors for the product used for searches"

![image](https://user-images.githubusercontent.com/88927411/132293028-a1581e40-a2ad-4e1e-96bd-08aacceabb51.png)

**Comment by olivermrbl** [comment]
Closed #88
