### ISSUE TITLE
Markdown Description

### ISSUE THREAD

**Issue by SaadBazaz** [medusajs/admin#753]
Hi!
I think the description within the Edit Product General Information should be a **markdown textarea**, so give users advanced control. 

<img width="834" alt="Screenshot 2022-11-02 at 4 21 53 PM" src="https://user-images.githubusercontent.com/51885228/199477282-166501af-99b7-4504-a1d1-628dac4404c6.png">

Similar to the markdown editor in GitHub.

ALTERNATIVE:
So, hear me out. 

It might be necessary to have a markdown (display) and non-markdown (SEO) input textarea. So why not both?
By default the Markdown textarea could have the same text as the non-markdown. 

If user selects a bool, it could make them different.

I've seen this concept in Meta's Business Suite. Could be great if it was prebuilt with Medusa.

https://user-images.githubusercontent.com/51885228/199481075-deb453d5-aabd-4482-96db-cf9b87ea7dee.mov

**Comment by olivermrbl** [comment]
@SaadBazaz - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!

**Comment by SaadBazaz** [comment]
Will do over the weekend. Thanks @olivermrbl !
