### ISSUE TITLE
Key value pairs in tags or attributes

### ISSUE THREAD

**Issue by SaadBazaz** [medusajs/admin#754]
## Problem
Sometimes I want to show special buttons on special products.
E.g. a "Preview" button on just a few products.

## Current workarounds
Adding them in Tags, that too with a custom format. E.g. preview__true (then split based on "__" on the frontend).

## Possible solutions
So it'd be great if we could have key-value pairs. 
e.g. 

```
[
{
   "key": "preview",
   "value": true,
}
]
```

OR 

```
[
{
   "preview": true
}
]
```

Or even add them in the tags
```
"metadata": {
    ...
    "tags": [
        {
            "id": "ptag_01GGVZVN43A7F767KZNFRNN1Q6",
            "created_at": "2022-11-02T10:58:12.000Z",
            "updated_at": "2022-11-02T10:58:12.000Z",
            "deleted_at": "",
            "value": "preview__true",
            "metadata": "",
        }
    ]
}
```

**Comment by SaadBazaz** [comment]
@olivermrbl Updated my issue desc. I've tried that, but it ain't it. 

Custom properties would be ideal. Simple key value pairs under a "properties" field.

**Comment by olivermrbl** [comment]
@SaadBazaz - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
