### ISSUE TITLE
Bug: Clicking 'Save' on a variant doesn't save it

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/admin#76]
**What?**
- The 'Save' Button in the edit variant modal calls the 'update' endpoint even for creation, but with id 'undefined'

Change the frontend by switching on the id, if it's undefined change the modal title and submit button to reflect the creation of a variant and the update of one

**Comment by rolwin100** [comment]
need help with this @olivermrbl with respect to the codebase walk through.

**Comment by olivermrbl** [comment]
Closed #89
