### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by raxelo** [medusajs/admin#765]
Add Dockerfile to be able to use the Medusa admin inside a docker container.

I think it could be referenced in the `docker-compose.yml`, in https://github.com/medusajs/medusa-starter-default, so that the starter repo also starts up an admin dashboard.

I opened this issue before creating a PR, but my intention is to contribute :)

**Comment by kasperkristensen** [comment]
Hi, we don't offer support for Docker, and won't be adding it. You can use this community-maintained repo if you are looking for a complete docker setup: https://github.com/medusajs/docker-medusa.
