### ISSUE TITLE
[Bug]: Infinity inviting one email address

### ISSUE THREAD

**Issue by LWJerri** [medusajs/admin#770]
Admins can send infinity invites to one email address without any errors. I think will be good to send an error notification if the email has already been invited.

URL: https://youtu.be/ah2cHHUIdHc

**Comment by olivermrbl** [comment]
@LWJerri - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
