### ISSUE TITLE
[Bug]: Admin can delete all admins in dashboard.

### ISSUE THREAD

**Issue by LWJerri** [medusajs/admin#771]
In the admin dashboard, the admin can delete all admins from the list, but I think it's not good and the admin dashboard must require at least 1 admin.

Yes, we can use CLI to create a new user with admin permissions, but this is not comfortable in production.

**Comment by olivermrbl** [comment]
@LWJerri - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
