### ISSUE TITLE
[Idea]: Allow upload avatars for admin accounts.

### ISSUE THREAD

**Issue by LWJerri** [medusajs/admin#774]
As storage, we can use S3 or store base64 in DB, because the image size is too small and it must fast load with base64.

**Comment by olivermrbl** [comment]
@LWJerri - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
