### ISSUE TITLE
[Bug]: Incorrect error notification when admin create group with already taken name

### ISSUE THREAD

**Issue by LWJerri** [medusajs/admin#785]
Admin receives error notification `Key (name)=(name) already exists.` when trying to create a group with identical names. We need to prevent this action because it can be confusing and send an error notification.

URL: https://youtu.be/oVNXs_9dZPo

**Comment by kasperkristensen** [comment]
It's the correct behavior for the admin to throw this error, as we should notify the users that something in their input is being rejected by the backend. I do agree that the error should be more "human friendly", something along the lines of "A customer group with that name already exists", but this should be handled by the backend, as we would not want to fetch every customer group (potentially +100) to check if the name is already taken before submitting the form. Closing this as there are already issues for better error messaging in the core repo :)
