### ISSUE TITLE
Bug: searching for customers via email crashes react-select

### ISSUE THREAD

**Issue by pKorsholm** [medusajs/admin#80]
**What?**
- When searching for a customer in draft order creation react-select crashes

**Comment by rolwin100** [comment]
i will take this up

**Comment by olivermrbl** [comment]
I think this relates to the backend due to SQLite not support ILIKE

**Comment by rolwin100** [comment]
nope its a frontend issue as well

**Comment by rolwin100** [comment]
check the PR https://github.com/medusajs/admin/pull/82 and merge it @olivermrbl
