### ISSUE TITLE
Error in medusa Admin when npm install

### ISSUE THREAD

**Issue by nazimboudeffa** [medusajs/admin#807]
Hi, I just have tested the new Admin with React and when I do `npm install` it displays an error

![6yyAeUxgBO](https://user-images.githubusercontent.com/1375686/204039882-0757e3d8-ef00-430d-9733-9cfe4f09bcbc.png)

I have solved that like what is said in the suggestion by running `npm install --legacy-peer-deps` and it worked

**Comment by chemicalkosek** [comment]
There's already a PR closed that will fix this.
