### ISSUE TITLE
[Feature] Define path alias for commonly used imports

### ISSUE THREAD

**Issue by ymaheshwari1** [medusajs/admin#808]
We should define a path alias in tsconfig for importing, as always using `../` is not a good option and also it will be easier to maintain.

Like for this `../../../../components/atoms/avatar` we can define something like `@/components/atoms/avatar` where @ means `/src`.

**Comment by olivermrbl** [comment]
@ymaheshwari1 - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
