### ISSUE TITLE
404 Error At Endpoint: //admin/analytics-configs/ on Admin

### ISSUE THREAD

**Issue by pavewaytech** [medusajs/admin#826]
Hello guys. 
Thank You for the unique architecture here.
I am implementing Medusajs for the first and I have issues with the Admin deployment. I have deployed the Server on Digital Ocean and the Admin Dashboard on Netlify following the guide but now I get redirected to the page to Opt-in to share my usage data. When I fill in the options and click continue nothing happens.

After inspecting the network tab I realized the request to the URI: //admin/analytics-configs/ returns a 404 status code.

![image](https://user-images.githubusercontent.com/45313829/206645917-a83312d8-bb48-4ae2-beee-e3a82712c577.png)

I even ran the command medusa telemetry --disable but to no avail because I still get redirected to the page. Please how can I remedy this issue?

**Comment by olivermrbl** [comment]
Thanks for reporting this @pavewaytech.

Can I get you to check that your Medusa URL in your environment variables does not contain a trailing `/`?

**Comment by ogvince** [comment]
> 

had same problem and it solved it

**Comment by ogvince** [comment]
> Thanks for reporting this @pavewaytech.
> 
> Can I get you to ensure that your Medusa URL in your environment variables does not contain a trailing `/`?

had same problem and it solved it

**Comment by olivermrbl** [comment]
Thanks for sharing @ogvince. Will close issue for now :)
