### ISSUE TITLE
Running Medusa admin in the cloud

### ISSUE THREAD

**Issue by rezabanitaba** [medusajs/admin#827]
This is likely not an issue per se, but I hope I can get some help here.
When running medusa admin on a cloud server ( ec2 instance ), Vite indicates that the interface is running at `Local:   http://localhost:7000/`
I am assuming that this should be accessible when replacing localhost with the public IP address of the instance. But I am unable to reach it when doing so. It is also not an issue with the security setting of the instance because it allows port 7000.
Do I need to use any extra flags when running `npm run start` ? such as --host ? 
Cheers

**Comment by The-Solomon** [comment]
Hi there, i`m as always late with an answer, but anyway.. My gues is that some kind of a default firewall(ufw most likely) blockes incoming connections to your host. You can read more about ufw installation and configration [here](https://linuxize.com/post/how-to-setup-a-firewall-with-ufw-on-ubuntu-18-04/). And by the way, you don't have to run a medusa-admin development server on a cloud. You can just build the react app and deploy it with nginx. [How to deploy react app with Nginx](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-react-application-with-nginx-on-ubuntu-20-04)
