### ISSUE TITLE
Error: Cannot find module 'node:path' when Running Medusa Admin

### ISSUE THREAD

**Issue by yogisaputro-fit** [medusajs/admin#833]
**Specs**
```
OS: Windows 10
Node version: 14.17.4
```
**Description**
I followed standard installation of Medusa Admin described here: https://docs.medusajs.com/admin/quickstart/
When I ran it locally using `npm run start`, an error occured with following message : `Error: Cannot find module 'node:path'`.
Meanwhile, my Medusa back-end runs without problems.

**Cause**
After a bit of digging, I found that [this commit](https://github.com/medusajs/admin/commit/6cfbc99298454b3330361eb82b878d673c52749f) added Vite version 3 to dev dependencies. According to [Vite](https://vitejs.dev/blog/announcing-vite3.html), version 3 requires at least Node version `14.18+` or `16+` 

**Resolution**
I upgraded Node to `14.18.6` and everything works normally. I just put it here if other folks had same problem. Hope this helps.

**Recommendation**
- Additional Node version requirement on Medusa Admin docs would be helpful.
- Maybe add tags if people want to go to previous version (if available)

Cheers

**Comment by kasperkristensen** [comment]
Hi @yogisaputro-fit, thanks for bringing it to our attention. Will definitely add it to the docs 🙂 Closing it here and reopening the issue for our docs.
