### ISSUE TITLE
[Feature Request] Using different Components for different Product Options 

### ISSUE THREAD

**Issue by SaadBazaz** [medusajs/admin#840]
Hey,

Currently, when using this admin panel with the [Nextjs Starter](https://github.com/medusajs/nextjs-starter-medusa/blob/dd1602584278f61b553cc8ae0ca6d82ba00a8a14/src/modules/products/components/product-actions/index.tsx), all options have this default "OptionSelect" Component:
![image](https://user-images.githubusercontent.com/51885228/208419316-e7298ee0-e4e8-447a-ac7f-2ff82d4af489.png)

It'd be great if we could specify the Component to use, for each product option. 
That way, for the "Set" option in the above example, I could specify "RadioButtons" and display:
![image](https://user-images.githubusercontent.com/51885228/208419523-20149aeb-c0fc-40bc-9c81-cb8c813a1056.png)

Hint: This can be done by adding generic metadata JSON to Product Options.

Just an ss of how the product looks like in the admin panel: 
![image](https://user-images.githubusercontent.com/51885228/208417561-ddad7d08-7f8e-4c8b-9e91-e7174925d5be.png)

**Comment by SaadBazaz** [comment]
After inspecting the structure of the Product object, I see there's a `metadata` field in there already:
![image](https://user-images.githubusercontent.com/51885228/208423677-1c458f15-f45d-42de-90b9-6277562760bf.png)

Can we have this editable in the following GUI?

![image](https://user-images.githubusercontent.com/51885228/208423806-fe958d76-5289-45e3-bfda-7f0a9f09d8e3.png)

**Comment by olivermrbl** [comment]
@SaadBazaz - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
