### ISSUE TITLE
quantity conditions for Pricelist are missing in UI

### ISSUE THREAD

**Issue by chemicalkosek** [medusajs/admin#861]
Docs state that you can create a condition on quantity for a pricelist:

_Minimum and/or maximum quantity: You can specify the minimum quantity, the maximum quantity, or both minimum and maximum quantities of a product variant required to be in the customer’s cart to apply a price in a price list._

There is no such UI in admin.

**Comment by olivermrbl** [comment]
Adding this to our backlog. This project has entered maintenance mode. Please submit the issue in our core repository, if you want to track it publicly.
