### ISSUE TITLE
[BUG]: I can't create a new region

### ISSUE THREAD

**Issue by Tygore** [medusajs/admin#862]
After last update medusajs/admin can't create new region. The button is not active. If I remove !isDirty (disabled={!isDirty || isLoading}) then the button is active and I can create it normally.
![i](https://user-images.githubusercontent.com/36534984/213137142-924054ae-0ed2-41f5-bb35-274b8922a921.jpg)

**Comment by kasperkristensen** [comment]
Hi @Tygore, 

I can't replicate your issue, could you provide some additional information such as which browser you are using, and what steps you took up until the error (did you create one region successfully and then you aren't allowed to create a second one, etc)?

**Comment by Tygore** [comment]
Hello,
I'm using the latest Chrome. There are no errors, just the button is not active (All required fields are filled).
Medusa Admin itself without any changes (clone from git). Changed Medusa Core (can changes affect medusa admin?). Before medusa admin update everything was fine.
I'll try to put everything standard on the weekend, without changes, and I'll try again and I'll be back with a report.

p.s. Thanks for the great product MedusaJS!

**Comment by Dakai** [comment]
Hi, I have the exact same issue, my setup is a Docker-based Medusa Server with the admin backend & a nextJS storefront made with ```npx create-medusa-app```.

**Comment by kasperkristensen** [comment]
Fixed in https://github.com/medusajs/admin/pull/897 issue was related to updating dependencies
