### ISSUE TITLE
[BUG] Error when disable sales channels

### ISSUE THREAD

**Issue by rrums123** [medusajs/admin#864]
Hello!
I got this error when disabled sales channels feature from Medusa project

`TypeORMError: sales_channel_id column was not found in the Order entity.`

To reproduce the issue:
- set `MEDUSA_FF_SALES_CHANNELS=false` on project ENV
- run admin panel, see any order

**Comment by olivermrbl** [comment]
Fixed in [#3357](https://github.com/medusajs/medusa/pull/3357)
