### ISSUE TITLE
Order date discrepancy

### ISSUE THREAD

**Issue by barnabycollins-s2z** [medusajs/admin#868]
Hey there,

Just wanted to ask a quick question: where I work, we have Medusa deployed and we use this console for administration. We've generally been very happy with it, but we've noticed that the order page always seems to backdate the order exactly 15 days. See screenshot below:

![image](https://user-images.githubusercontent.com/115482091/213686675-014a8ae2-392d-4722-b597-acac69b53562.png)

We create the orders using the API, in case that's useful, and we're in the UK (so current timezone is GMT). This isn't a major issue, as the API responses all show the correct timings, but we thought we should mention it here.

Is this likely to be a problem with our deployment / API usage, or is it something that needs fixing in the admin console source code?

Thanks in advance! :)

**Comment by olivermrbl** [comment]
@barnabycollins-s2z Great to hear that you are happy with Medusa so far. 

This issue was [resolved back in November](https://github.com/medusajs/admin/pull/758) and has been pushed to `main` so I would assume pulling the upstream changes should do the job.

Let me know!
