### ISSUE TITLE
Weird port issue on macOS resulting in a blank page

### ISSUE THREAD

**Issue by henninghorn** [medusajs/admin#871]
I recently tried setting up Medusa locally, followed the quickstart guide etc.
After starting the server and the admin, I opened up http://localhost:7000 and got a blank page.

Instead of opening the page in Firefox, I tried opening the page in Safari. Everything suddenly worked fine.

Upon further inspection I noticed I got a 403 error, with a response header stating `Server: AirTunes/XXX.YY.Z`.
This led me to: https://developer.apple.com/forums/thread/682332

It turns out, that if you have AirPlay-receiver turned on on your Mac, it may listen on port 5000 and 7000.
This caused the blank page with the 403 error.

I just thought you should know about this potential issue.

**Comment by StephixOne** [comment]
Thank you for reporting it. It's something we've intermittently seen ourselves and have been considering altering the default vite dev port.

**Comment by pedropaf** [comment]
Same for me, I updated the port to use 7001 and it worked.

**Comment by olivermrbl** [comment]
@henninghorn Thanks for letting us know. Will close this issue, but hopefully it'll remain as a source of troubleshooting for others with the same problem :)

**Comment by aaron5670** [comment]
Thanks, I had the same issue! Fixed by changing the port to 7001. 😄
