### ISSUE TITLE
Admin is not able to call the API due to CORS issue

### ISSUE THREAD

**Issue by nhatanhit** [medusajs/admin#893]
Hello everyone. 
I tried writing new API endpoint with the full URL `http://localhost:9000/admin/designs/1/10`  and I can load its data when I run my API in Postman, or even in a new tab of the browser. (see below screenshot )
![image](https://user-images.githubusercontent.com/11988070/218314625-82469033-185e-4240-a817-f0239ff29bbf.png)

However , when loading  that URL in medusa admin, I got following issue 
![image](https://user-images.githubusercontent.com/11988070/218314532-bbcba3d3-c859-4062-bfa1-5a1e7aeb0263.png)

And plus, my new API endpoint isn't protected by CORS at the moment, It's freely to access from postman and my browser.
![image](https://user-images.githubusercontent.com/11988070/218314707-fe9e3e0e-a949-4b18-b586-fc9c9e4e375d.png)

Whenever loading my API in admin, following request log in backend is generated 

`OPTIONS /admin/designs/1/10 HTTP/1.1" 200 8 "http://localhost:7000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36` (It should be  GET)

**Some solutions I tried** 

- I thought the API is fine ( I am able to access it through Postman / browser tab ) , so i tried replacing current  Axios in Admin with newer version, but it's still no luck. 
- I tried clearing cache/ cookies  or try open admin in other browsers, but it's still not work 

Can you please help to check anything I missed ? Any help will be appreciated. 
Thank you

**Comment by olivermrbl** [comment]
I believe you are missing a CORS configuration of your endpoint. 

Something like:
```
router.options("/admin/designs/:offset/:limit", cors(corsOptions))
```

[Read more in our documentation](https://docs.medusajs.com/advanced/backend/endpoints/add).

**Comment by nhatanhit** [comment]
Hi @olivermrbl 
Actually , I tried adding CORS middleware for  new API endpoint  as well, but it didn't work. 
![image](https://user-images.githubusercontent.com/11988070/218318302-73319f18-365b-497c-a451-d98c6d963322.png)
my medusa config 
![image](https://user-images.githubusercontent.com/11988070/218318340-4e5ca3b2-30f8-419e-9203-8602b38c3d74.png)

And still no luck for me
![image](https://user-images.githubusercontent.com/11988070/218318373-e2a604b0-0d9c-4e5d-b57b-e6a197010712.png)

That's why I tried removing the CORS middleware then. 

Please help.

**Comment by olivermrbl** [comment]
Can I get you to try the following:
```
const { configModule } getConfigFile(rootDirectory, "medusa-config")
...
router.options("/admin/designs/:offset/:limit", cors(corsOptions))
router.get("/admin/designs/:offset/:limit", cors(corsOptions), async (req, res) => {
   ...
})
```

**Comment by nhatanhit** [comment]
Thank you so much 
The `router.options` is what I am missing. 
Thanks again
