### ISSUE TITLE
[Feature] Dark Theme

### ISSUE THREAD

**Issue by 0xZ0uk** [medusajs/admin#898]
### Overview
**Been using Medusa for a week now, mostly trying it out. Really enjoy it so far, but has someone who's working his side projects late at night, I could really use a dark theme. That's why I'm contributing it!**

Took the liberty of reaching out to Medusa's designer Ludvig Rask, on Twitter, seeing he had some work in progress towards a dark theme. I've worked with his WIP, and extended the color range you had, to include two new colors schemes "Stone" and "Purple", leaving the "Grey" and "Violet" used in the current light theme untouched.

Most of the work is already done, only some testing and potential fixes left to do.

### Give a hand

**Also looking for suggestions on where to put the theme switch, currently I have it in the bottom of the sidebar, but think it may be easily missed. Also we could have no theme switch, and just have Medusa adapt to the preferred color scheme set by the user in his browser/OS.** 

### Sneak peak
![image](https://user-images.githubusercontent.com/81437712/218975736-9bcb7bd2-31ec-4222-a9f3-d797cc8bab68.png)

**Comment by olivermrbl** [comment]
@0xZ0uk - By the end of March, we will have moved the admin project to our core [monorepo](https://github.com/medusajs/medusa), and maintenance of this repository will come to a halt shortly after. Therefore, please move your feature request (if still relevant) to our GitHub Discussions - **not issues** - to centralize requested improvements for all our projects.

Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!

**Comment by 0xZ0uk** [comment]
@olivermrbl Had already done that has per your contributions guide. Has for the dark theme itself, I finished the development, but have had no time to test it since.
https://github.com/medusajs/medusa/discussions/3259
