### ISSUE TITLE
Suggestion: add product bulk delete feature

### ISSUE THREAD

**Issue by stephane-klein** [medusajs/admin#916]
Do you plan to add product bulk delete feature?

<img src="https://user-images.githubusercontent.com/54498080/226395577-777c475d-559b-4f6d-a8dd-11515927c321.png" width="1000" />

**Comment by olivermrbl** [comment]
@stephane-klein - This project has entered maintenance mode. We are moving feature requests to GitHub Discussions to track the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
