### ISSUE TITLE
Suggestion: allow the creation of collection directly from "new product" page

### ISSUE THREAD

**Issue by stephane-klein** [medusajs/admin#917]
Do you plan to create a collection directly from the "new product" page?

<img src="https://user-images.githubusercontent.com/54498080/226407489-348658cd-602a-41de-b87f-77de0baa1765.png" width='800' />

**Comment by olivermrbl** [comment]
@stephane-klein - This project has entered maintenance mode. We are moving feature requests to GitHub Discussions to track the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
