### ISSUE TITLE
alt tag support for product images to improve accessibility

### ISSUE THREAD

**Issue by abishekmuthian** [medusajs/admin#918]
Greetings medusa team and contributors,

As of now Admin portal doesn't seem to support setting the alt description for the product images.

Alt tags are very important for visually impaired users to understand the images shown in their screen through various screen reading tools.

Currently the alt tags are set "Product #N" in the storefront with N being the index of the product images.

I feel the alt tag input can be added to the dialog where the images are uploaded.

**Comment by olivermrbl** [comment]
@abishekmuthian - This project has entered maintenance mode. We are moving feature requests to GitHub Discussions to track the most requested features (using the upvote mechanism) and streamline GitHub Issues around bugs. Could I ask you to re-open your request here: https://github.com/medusajs/medusa/discussions/categories/feature-requests

Thanks!
