### ISSUE TITLE
Re-order categories list bug [Test-categories] Branch

### ISSUE THREAD

**Issue by pumbaaisacoder** [medusajs/admin#919]
Hello, what is the purpose exactly for use "rank" in update productCategories list?

I cannot save my new categories order, it works only when I remove it. 

`await client.admin.productCategories.update(dragItem.id, {
        parent_category_id: parentId,
        rank,
      })`

https://github.com/medusajs/admin/blob/4cfa3323e85262193be0b5b908b756aceb122e47/src/domain/product-categories/components/product-categories-list.tsx#L51

**Comment by olivermrbl** [comment]
@pumbaaisacoder What admin repository are you using? The latest changes to Product Categories can be found in the core repository and are part of the [Release Candidate for 1.8](https://github.com/medusajs/medusa/releases/tag/v1.8.0-rc.0). Therefore, you might experience issues with our newest features, if you are using this repository which will be deprecated very soon.

@riqwan Will you assist here?

**Comment by riqwan** [comment]
@pumbaaisacoder rank is a column that we use to set order under a category node. Categories won't work correctly in the admin repository you've linked, you will have to use the admin from core. Its pretty quick to get started, the release candidate link shared by Oliver has the instructions.
