### ISSUE TITLE
CSV Template URL is pointing to wrong endpoint when using backend with admin plugin

### ISSUE THREAD

**Issue by andresrivero** [medusajs/admin#923]
When using the admin portal on the backend via the plugin option, you connect to it using URL:PORT/app (by default). Most things work but on the product list page, there is an Import Products modal button, which has a CSV template link at the bottom. This link points to: http://URL:PORT/temp/product-import-template.csv
But with the admin being a plugin, it should be ...PORT/app/temp/product-import-template.csv

Adding the /app/ to the URL in the middle allows you to fix it and download the template. On an installation where I have a standalone admin this issue doesn't exist.

**Comment by olivermrbl** [comment]
Please open this issue in our [core repository](https://github.com/medusajs/medusa), as it relates to the admin plugin.
