### ISSUE TITLE
Uncaught SyntaxError: The requested module '/@fs/Users/mitchellewulonu/demo-medusa-admin/node_modules/react-dom/index.js?v=b90c7b1b' does not provide an export named 'flushSync' (at index.module.js?v=b90c7b1b:3:9)

### ISSUE THREAD

**Issue by mitchellewulonu** [medusajs/admin#926]
Hello,

I'm following Option 2: Install and Serve Admin Separately at https://docs.medusajs.com/admin/quickstart but im getting the following error and admin site doesn't load

**Error**
Uncaught SyntaxError: The requested module '/@fs/Users/mitchellewulonu/demo-medusa-admin/node_modules/react-dom/index.js?v=b90c7b1b' does not provide an export named 'flushSync' (at index.module.js?v=b90c7b1b:3:9)

**Screenshot**
![Screenshot 2023-04-10 at 00 10 40](https://user-images.githubusercontent.com/33165742/230801459-ef043e66-e4bb-45fb-8ab1-64fc8904f672.png)

I think there is a bug. Could you please advise on this and also how to deploy to Vercel with option 2

Thank you for your attention to this issue.

**Comment by olivermrbl** [comment]
Please move this issue to our [core repository](https://github.com/medusajs/medusa), as this admin project is in maintenance mode and will soon be deprecated.
