### ISSUE TITLE
Unexpected Application Error!

### ISSUE THREAD

**Issue by Gunkev** [medusajs/admin#927]
Hello,
I have cloned the Medusa admin dashboard twice but I am getting this screen 
![ui error](https://github.com/medusajs/admin/assets/36812576/76f651bf-6dba-434f-90f0-eb5e35ca1289)

There is no error in the console.

**Comment by olivermrbl** [comment]
This project is no longer maintained. See [this guide](https://docs.medusajs.com/admin/quickstart) on how to use our new admin system.
