### ISSUE TITLE
Team user invite link is incorrect

### ISSUE THREAD

**Issue by felipemullen** [medusajs/admin#929]
When sending an invite to a new user via the UI, the invite link is broken:

Admin ui path is configured as below
```typescript
{
    resolve: '@medusajs/admin',
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {
        autoRebuild: true
    }
},
```

Local address appears as expected

<img width="380" alt="image" src="https://github.com/medusajs/admin/assets/3488482/65b9247d-29ef-44f7-b806-f942a68c7c71">

When copying the link in the menu OR using the link sent to the email as seen in this image

<img width="443" alt="Screen Shot 2023-05-24 at 3 46 32 PM" src="https://github.com/medusajs/admin/assets/3488482/171652b7-e94c-46e6-b219-52c09008defa">

The result is the following link. **Note that is is missing `/app` from the link.**
```text
http://localhost:9000/invite?token=<token value>
```

I have attempted to add `path: 'adm'` to the plugin import options, but the same error occurs

**Comment by olivermrbl** [comment]
Please create this issue on our main GitHub repository.

Regarding your issue, you can specify the invite link in your store settings. 

Go to "Settings" > "Store Details" and add the link template that fits your case. 

It will look something like: 
<img width="695" alt="CleanShot 2023-05-25 at 10 28 44@2x" src="https://github.com/medusajs/admin/assets/59018053/5baa4ab6-97ed-4d31-bdbb-46e625d681b1">
