### ISSUE TITLE
customers search is throwing 500 error

### ISSUE THREAD

**Issue by rolwin100** [medusajs/admin#94]
In your local go to [http://localhost:7000/a/customers?limit=20&offset=0&q=hi](http://localhost:7000/a/customers?limit=20&offset=0&q=hi) the search will fail with 500 status code. Probably backend issue.

**Comment by olivermrbl** [comment]
Thanks for reporting @rolwin100 . This is likely due to your local setup using SQLite. `ILIKE` is not a feature supported in SQLite and we use that for our search functionality. There is already an issue on this in @medusajs/core .

**Comment by rolwin100** [comment]
got it
