### ISSUE TITLE
orders page clicking on all tab after applying filter resets the applied filter

### ISSUE THREAD

**Issue by rolwin100** [medusajs/admin#96]
go to the orders page [http://localhost:7000/a/orders](http://localhost:7000/a/orders) apply the filters navigate to the Completed tab and click on the orders tab again you will notice that the filter has been reset.

<img width="350" alt="Screenshot 2021-09-09 at 9 08 53 AM" src="https://user-images.githubusercontent.com/20384864/132618460-70bb6ac0-b6f3-43cb-b5df-5e012af6014e.png">

**Comment by olivermrbl** [comment]
Can you elaborate a bit more? Maybe provide a gif :) 

As far as I understand, this is intentional behavior.

**Comment by rolwin100** [comment]
lets say I applied a few filter and then I change to incomplete tab the filters applied will still be present but again when I come back to all the filter applied are removed.
